Require Export UniMath.Bicategories.ComprehensionCat.BicatOfCompCat.DispCatTerminal.
Require Export UniMath.Bicategories.ComprehensionCat.BicatOfCompCat.FibTerminal.
Require Export UniMath.Bicategories.ComprehensionCat.BicatOfCompCat.CompCat.
Require Export UniMath.Bicategories.ComprehensionCat.BicatOfCompCat.FullCompCat.
