(* This file has been auto-generated, do not edit it. *)
Require Export UniMath.Algebra.BinaryOperations.
Require Export UniMath.Algebra.Monoids_and_Groups.
Require Export UniMath.Algebra.RigsAndRings.
Require Export UniMath.Algebra.RigsAndRings.Ideals.
Require Export UniMath.Algebra.Domains_and_Fields.
Require Export UniMath.Algebra.DivisionRig.
Require Export UniMath.Algebra.Apartness.
Require Export UniMath.Algebra.ConstructiveStructures.
Require Export UniMath.Algebra.Archimedean.
Require Export UniMath.Algebra.Lattice.
Require Export UniMath.Algebra.IteratedBinaryOperations.
Require Export UniMath.Algebra.Free_Monoids_and_Groups.
Require Export UniMath.Algebra.Tests.
Require Export UniMath.Algebra.Modules.Core.
Require Export UniMath.Algebra.Modules.Submodule.
Require Export UniMath.Algebra.Modules.Multimodules.
Require Export UniMath.Algebra.Modules.Examples.
Require Export UniMath.Algebra.Modules.
Require Export UniMath.Algebra.Matrix.
