(* This file auto-generated by refresh-export-files.sh, *)
(* and may be re-auto-generated in future, *)
(* so any edits made by hand may be lost. *)
Require Export UniMath.Tactics.Abmonoids_Tactics.
Require Export UniMath.Tactics.Groups_Tactics.
Require Export UniMath.Tactics.Monoids_Tactics.
Require Export UniMath.Tactics.Nat_Tactics.
Require Export UniMath.Tactics.Utilities.
