(* This file auto-generated by refresh-export-files.sh, *)
(* and may be re-auto-generated in future, *)
(* so any edits made by hand may be lost. *)
Require Export UniMath.Folds.UnicodeNotations.
Require Export UniMath.Folds.aux_lemmas.
Require Export UniMath.Folds.folds_isomorphism.
Require Export UniMath.Folds.folds_pre_2_cat.
Require Export UniMath.Folds.folds_precat.
Require Export UniMath.Folds.from_precats_to_folds_and_back.
