name: Generate Documentation

on:
  workflow_run:
    workflows: [CI Build UniMath]
    types:
      - completed

jobs:
  html-docs:
    name: HTML Documentation
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache/restore@v4
        with:
          path: dune-cache
          restore-keys: UniMath-Linux-coq-latest-

      # Tar workspace files
      - name: 'Tar the entire directory'
        run: tar -cf build.tar .

      # We upload build artifacts for use by documentation
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build.tar
